version: "3"
services:
  proto:
    # command: ./proto/scripts/protoc.sh
    build:
      context: ./docker/proto
      dockerfile: Dockerfile
    volumes:
      - .:/proto
    tty: true

  server:
    command: air -c .air.toml
    build:
      context: ./docker/golang
      dockerfile: Dockerfile
    volumes:
      - ./src:/go/src/go_grpc
    depends_on:
      - proto
