version: "3"
services:
  proto:
    command: ./proto/protoc.sh
    build:
      context: ./docker/proto
      dockerfile: Dockerfile
    volumes:
      - .:/proto
    tty: true

  server:
    command: air -c .air.toml
    build:
      context: ./docker/server
      dockerfile: Dockerfile
    volumes:
      - ./server:/go/src/go_grpc
    depends_on:
      - proto
    ports:
      - 8080:8080
